export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PUCHASE_INIT';

export const LOAD_USER_ORDERS_START = 'LOAD_USER_ORDERS_START';
export const LOAD_USER_ORDERS_SUCCESS = 'LOAD_USER_ORDERS_SUCCESS';
export const LOAD_USER_ORDERS_FAIL = 'LOAD_USER_ORDERS_FAIL';